In [1]:
from pymultifracs.simul import mrw
import numpy as np

X = mrw(shape=(65536, 2), H=0.8, lam=0.3, L=65536)

In [2]:
X

array([[ 1.65448578e-07, -2.13790410e-04],
       [-6.06888586e-05, -2.88236038e-04],
       [-2.25850996e-04, -2.79136456e-04],
       ...,
       [ 6.61906068e-01,  4.80580782e-01],
       [ 6.61838233e-01,  4.80580432e-01],
       [ 6.61735562e-01,  4.80464194e-01]])

In [3]:
wt_name = 'db2'
p_exp = 2
j2 = np.log2(65536) - 3

gamint = 0.0
wtype = True

In [4]:
from pymultifracs.wavelet import wavelet_analysis

In [5]:
from importlib import reload

In [6]:
import pymultifracs.wavelet
reload(pymultifracs.wavelet)
from pymultifracs.wavelet import wavelet_analysis

In [7]:
X.shape

(65536, 2)

In [8]:
WT1 = wavelet_analysis(X[:, 0], p_exp=p_exp, j2=j2, gamint=gamint, weighted=wtype)

In [9]:
WT2 = wavelet_analysis(X[:, 1], p_exp=p_exp, j2=j2, gamint=gamint, weighted=wtype)

In [10]:
from pymultifracs.estimation import estimate_hmin

In [11]:
estimate_hmin(WT1.wt_coefs, 3, WT1.j2_eff, wtype)[0].min()

0.4677584240290453

In [12]:
estimate_hmin(WT2.wt_coefs, 3, WT2.j2_eff, wtype)[0].min()

0.563436643971557

In [44]:
import pymultifracs.bivariate.bivariate_cumulants
reload(pymultifracs.bivariate.bivariate_cumulants)
from pymultifracs.bivariate.bivariate_cumulants import BiCumulants

In [45]:
BiCum = BiCumulants(WT1.wt_leaders, WT2.wt_leaders, n_cumul=2, j1=3, j2=WT1.j2_eff, wtype=True)

In [46]:
BiCum.log_cumulants

array([[ 0.00000000e+00,  8.50792414e-01, -1.30198528e+01],
       [ 8.43366184e-01,  1.11594905e-02, -1.55566702e-01],
       [-1.29258705e+01, -1.79972855e-01,  2.70215343e+00]])

In [47]:
BiCum.values[0, 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
BiCum.rho_mf

-0.0008602237466420582

In [26]:
import pymultifracs.bivariate.bivariate_structurefunction
reload(pymultifracs.bivariate.bivariate_structurefunction)
from pymultifracs.bivariate.bivariate_structurefunction import BiStructureFunction

In [27]:
?BiStructureFunction

Init signature:
BiStructureFunction(
    mrq1: dataclasses.InitVar[MultiResolutionQuantity],
    mrq2: dataclasses.InitVar[MultiResolutionQuantity],
    j1: int,
    j2: int,
    q1: numpy.ndarray,
    q2: numpy.ndarray,
    wtype: bool,
) -> None
Docstring:      BiStructureFunction(mrq1: dataclasses.InitVar[MultiResolutionQuantity], mrq2: dataclasses.InitVar[MultiResolutionQuantity], j1: int, j2: int, q1: numpy.ndarray, q2: numpy.ndarray, wtype: bool)
File:           ~/Multifracs/pymultifracs/pymultifracs/bivariate/bivariate_structurefunction.py
Type:           type
Subclasses:     


In [28]:
BiSF = BiStructureFunction(WT1.wt_coefs, WT2.wt_coefs, j1=3, j2=WT1.j2_eff, q1=np.array([2]), q2=np.array([2]), wtype=True)

In [30]:
BiSF.H

1.667301848096868

In [25]:
BiSF.zeta

array([[3.3346037]])